### ISSUE TITLE
Request for conv2d and dropout layers

### ISSUE THREAD

**Issue by ViaAdmin** [CrowdStrike/tf2rust#1]
Hello, I am a user of tf2rust and I appreciate your work on this tool. I have a TensorFlow model that uses conv2d and dropout layers, but I found that tf2rust does not support these layers yet. I wonder if you have any plans to implement them in the future, or if you can provide some guidance on how to do it myself. Thank you for your attention and response.

**Comment by makr11st** [comment]
Hi @ViaAdmin , thank you for the interest in the project.

There are a few steps involved to add a new layer type, I will add more thorough guide in the next few days, but for a general guide please try to follow these steps:
1. Add a new layer node in the `tf2rust/nodes`
2. Add imports and `LAYERS_DICTIONARY` in the `tf2rust/constants.py` 
3. Add new layer in the [tf-layers](https://github.com/CrowdStrike/tf-layers/tree/main/src) to match 
4. Expose the new layer in the `tf-layers`

For the `conv2d` you can take as an example the `conv1d` implementation.

I hope it helps and if you have more questions feel free to ask more questions.
