### ISSUE TITLE
Possible quantization support

### ISSUE THREAD

**Issue by SkBlaz** [CrowdStrike/tf2rust#5]
Hello! First off, amazing project. Learned a lot by reading through source, it is really well documented/clear. I do have a question r.e. development -- is this project finished/done? If not, did you plan to incorporate any form of weight quantization at any point? This could offer another concrete boost. 

Further, are you aware of performance pitfalls of ndarray vs. ordinary slices [1]? Was this considered during dev? If so, what led you to ndarray? Asking more or less out of interest :) 

[1] https://www.reidatcheson.com/rust/ndarray/performance/2022/06/11/rust-ndarray.html

**Comment by makr11st** [comment]
Hi @SkBlaz thank you for your feedback and I'm glad you like the project. I'll answer of your questions for you.

>  is this project finished/done?
Depends how you consider the doneness of a project, but in case of `tf2rust` we can say that technically the project is mostly "done" as it implements the requirements but is not necessarily "finished", there is still a lot of features which could be implemented.

>  did you plan to incorporate any form of weight quantization at any point?
At the moment we do not plan to add quantization to this project, but if you are interested to work on this feature set I would be more than happy to assist and provide all necessary help.

> are you aware of performance pitfalls of ndarray vs. ordinary slices [1]? Was this considered during dev? If so, what led you to ndarray?

The `tf2rust` started as a research project and at the time use of `ndarray` and the ecosystem was reasonable decision and we were aware of the "pitfalls", yes. `ndarray` is very convenient for handling multidimensional arrays.
In terms of performance it's a different subject as performance is not the main goal of this project (if it was we would probably go with either other implementation of the computational features or non Rust option).

**Comment by SkBlaz** [comment]
Thanks, the rationale is sound! Will get back to you with a PR or two, if we go down that path :+1:
